### ISSUE TITLE
Crash on concurrent queries

### ISSUE THREAD

**Issue by LukasPukenis** [brave/adblock-rust#101]
Hello. Is this library thread safe? I'm using this library together with `adblock-rust-ffi` from Brave's repository and so far it was working well until I hit some crashes. Upon investigation I have achieved 100% reproducability when simply querying the `engine_match(...)` in a multithreaded code. I fixed this crash in my code by simply locking a mutex around `engine_match(...)`

It may just be that the library is not thread safe - given examples are of a single threaded code. Maybe my assumptions were just wrong :)

Crash details:
```
thread '<unnamed>' panicked at 'already borrowed: BorrowMutErrorthread '<unnamed>thread '<unnamed>' panicked at '' panicked at 'already borrowed: BorrowMutErroralready borrowed: BorrowMutErrorthread '<unnamed>thread '', <unnamed>' panicked at '', /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/cell.rs:-> 50
thread '/rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/cell.rs878::878:9already borrowed: BorrowMutError
', /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/cell.rs:', 9878-> 51

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
' panicked at ':already borrowed: BorrowMutError', -> 52
/rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/cell.rs:878:9
9
<unnamed>/rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/cell.rs' panicked at 'already borrowed: BorrowMutError', /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/cell.rs:878:9
:878:9
SIGABRT: abort
PC=0x7fff6f4be2c2 m=9 sigcode=0
...
```

**Comment by AndriusA** [comment]
It is not thread safe, no - when used across the FFI we don't want Rust code to create its own threads.

It might be possible to fix what you're running into here:
https://github.com/brave/adblock-rust/blob/master/src/filters/network.rs#L208

by changing `Rc` and `RefCell` to the roughly-equivalent thread safe `Arc` and `RwLock` (here as well as the bit that does the interior mutation).

I'm not sure that it will make everything run correctly across the FFI boundary though.

**Comment by LukasPukenis** [comment]
@AndriusA Thanks for explaining. If it's not thread safe by design that's fine i guess. Thanks: )
