### ISSUE TITLE
YouTube ads not being blocked V1.10.90

### ISSUE THREAD

**Issue by Mellelmejor** [brave/adblock-rust#104]
YouTube ads appear without the possibility of being skipped. Cleaning browsing data (cache, cookies, whatever else) doesn't work.

The issue started about 10 days ago.

The only way to skip the ads is reloading the website.

**Comment by antonok-edm** [comment]
@Mellelmejor @hamburger6 this was an issue in `brave-core`, not in `adblock-rust`, essentially due to a race condition that primarily caused issues when opening youtube videos in new tabs.

The [fix](https://github.com/brave/brave-core/pull/5955) will be available in the next Brave release.
