### ISSUE TITLE
Switch to uBO lists + brave-unbreak.txt

### ISSUE THREAD

**Issue by pes10k** [brave/adblock-rust#113]
As a forcing function to get us to keep pushing changes upstream, and to improve web compat, adblock-rust should by default use the exact same set of lists uBO does, plus braves single additions list.

So the full set of lists would be:

- https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt
- https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters-2020.txt
- https://github.com/uBlockOrigin/uAssets/blob/master/filters/badware.txt
- https://github.com/uBlockOrigin/uAssets/blob/master/filters/privacy.txt
- https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt
- https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt
- https://easylist.to/easylist/easylist.txt
- https://easylist.to/easylist/easyprivacy.txt
- https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext 
- https://easylist-downloads.adblockplus.org/malwaredomains_full.txt
- http://www.malwaredomainlist.com/hostslist/hosts.txt

**Comment by fmarier** [comment]
Please also remove the no-longer-shipped lists from https://github.com/brave/brave-core/tree/master/components/third_party/adblock/lists once this change lands.

**Comment by ryanbr** [comment]
A few options we get implement this:

1. We could removed any Easylist/Easyprivacy rules. Leaving only differences. https://secure.fanboy.co.nz/disconnect.lists.txt
2. Remove all Disconnect filters, except Social (facebook/twitter/linkedin) and select domains.

We can re-use the exisiting filename `https://github.com/brave/adblock-lists/blob/master/brave-disconnect.txt`  to make the transition easier.

**Comment by antonok-edm** [comment]
> - https://easylist-downloads.adblockplus.org/malwaredomains_full.txt
> - http://www.malwaredomainlist.com/hostslist/hosts.txt

These two lists required support for hosts format lists, which was just released in v0.3.0. However, uBO was recently updated to use https://gitlab.com/curben/urlhaus-filter instead - an official version of this list is provided in the standard format.

**Comment by antonok-edm** [comment]
Closing, as of #120 this is handled in https://github.com/brave/adblock-resources rather than here.
