### ISSUE TITLE
Support for abort-on-stack-trace scriptlet

### ISSUE THREAD

**Issue by ryanbr** [brave/adblock-rust#143]
Support for the new abort-on-stack-trace scriptlet

From the related talk: https://github.com/AdguardTeam/Scriptlets/issues/82

https://github.com/brave/uBlock/commit/b735ac6b6abab7d5f45e15bbba3b4ba6cbf43935
https://github.com/brave/uBlock/commit/793e2c78963ba86c8d36b950807ce952f7199c1f
https://github.com/brave/uBlock/pull/20/commits/365b3f7f839193df29244fcfc42c4c22afa4f528

**Comment by antonok-edm** [comment]
Resolved by brave/uBlock#20. Although, the related discussion looks very interesting and we should keep an eye on the new scriptlet syntax.
