### ISSUE TITLE
Support nth-of-type and upward (Cosmetic)

### ISSUE THREAD

**Issue by ryanbr** [brave/adblock-rust#145]
Since youtube has a specifically target css ad element, `youtube.com##ytd-display-ad-renderer:upward(2)` in https://github.com/brave/brave-browser/issues/11955

```
Filters.txt (Upward 39 lines, nth-of-type:  26 lines)
Filters-2020.txt (Upward 10 lines, nth-of-type:  10 lines)
```

**Comment by ryanbr** [comment]
matches-css:  

`chip.de###CR > div[id^="G3"]:matches-css(grid-template-rows: /^\d+px/):style(grid-template-rows: auto !important;)`

**Comment by antonok-edm** [comment]
Added as of https://github.com/brave/adblock-rust/pull/388
