### ISSUE TITLE
Error when installing from npm

### ISSUE THREAD

**Issue by eerkaijun** [brave/adblock-rust#151]
Hi, I got an error when trying to install from npm registry. Any ideas why? 

`npm install adblock-rs`

```
> adblock-rs@0.3.4 install /home/kai/winterwell/cmp-browser-plugin/node_modules/adblock-rs
> neon build --release

neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adblock-rs@0.3.4 install: `neon build --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adblock-rs@0.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by antonok-edm** [comment]
I believe this error means that `npm` couldn't find the `cargo` executable on your computer. `adblock-rust` is written mostly in Rust, so it requires the Rust build tools installed in order to run.

**Comment by eerkaijun** [comment]
@antonok-edm  thanks! Managed to get the rust package and solved it. Another question is that when I am trying to import module 
`const AdBlockClient = require('adblock-rs');`
it has an error "Could not find a declaration file for module 'adblock-rs'. " This seems like an error for typescript libraries. 

Is this library compatible for javascript?

**Comment by antonok-edm** [comment]
That's a Typescript error, there are currently no type declarations for this library. It should work in normal Javascript.

If you're interested in writing type declarations, please submit a PR - I'd be happy to add them in!

**Comment by eerkaijun** [comment]
Sure, I'll just close off this issue then :)
