### ISSUE TITLE
Blocking elements stopped working

### ISSUE THREAD

**Issue by ugultopu** [brave/adblock-rust#159]
# Versions
- macOS 10.15.7
- Brave 1.21.73

# Steps to Reproduce
- Go to https://github.com/.
- Log out.
- Right click anywhere, select "Brave", select "Block element via selector".
- Type `header` in the pop-up and select "OK". The header should be gone now.
- Refresh the page. The header is back, although it should have been blocked.

**Comment by antonok-edm** [comment]
Thanks for the report! I believe this is only an issue with how Brave Browser wraps around `adblock-rust`, and I believe it's related to [this issue](https://github.com/brave/brave-browser/issues/14458) - so I'll close this for now. But feel free to reopen if you find a specific problem with the Rust APIs here :smiley:
