### ISSUE TITLE
Punycoding inconsistently applied when generating Apple Content Blocking data

### ISSUE THREAD

**Issue by bmwalters** [brave/adblock-rust#161]
## Problem
Thank you for your work on adblock-rust. I have experienced an issue with the `content_blocking` module inconsistently applying Punycoding to Internationalized Domain Names, for example `allestörungen.at` which was recently mentioned in EasyPrivacy (https://github.com/easylist/easylist/commit/10b8fc53bc500c17f6a1458ceaf52ec08c136afb).

This poses a problem for consuming adblock-rust-generated Apple Content Blocking data on iOS. Without punycoding, the following error occurs: `"Rule list compilation failed: Domains must be lower case ASCII. Use punycode to encode non-ASCII characters."`

## Test Case
https://github.com/bmwalters/adblock-rust/commit/2aca23cadd4ecbf876180e9cb1bf403eb17d7814

<details>

<summary>:paperclip: Diff</summary>

```diff
diff --git a/src/content_blocking.rs b/src/content_blocking.rs
index 4f1f403..6d441a7 100644
--- a/src/content_blocking.rs
+++ b/src/content_blocking.rs
@@ -794,6 +794,17 @@ mod ab2cb_tests {
                 ]
             }
         }]"####);
+        test_from_abp("||allestörungen.at^$third-party", r####"[{
+            "action": {
+                "type": "block"
+            },
+            "trigger": {
+                "url-filter": "^[^:]+:(//)?([^/]+\\.)?xn--allestrungen-9ib\\.at",
+                "load-type": [
+                    "third-party"
+                ]
+            }
+        }]"####);
         test_from_abp("||anet*.tradedoubler.com^$third-party", r####"[{
             "action": {
                 "type": "block"
@@ -1019,6 +1030,18 @@ mod ab2cb_tests {
                 ]
             }
         }]"####);
+        test_from_abp("@@||googletagservices.com/tag/js/gpt.js$domain=allestoringen.nl|allestörungen.at", r####"[{
+            "action": {
+                "type": "ignore-previous-rules"
+            },
+            "trigger": {
+                "url-filter": "^[^:]+:(//)?([^/]+\\.)?googletagservices\\.com/tag/js/gpt\\.js",
+                "if-domain": [
+                    "*allestoringen.nl",
+                    "*xn--allestrungen-9ib.at"
+                ]
+            }
+        }]"####);
         test_from_abp("@@||advertising.autotrader.co.uk^$~third-party", r####"[{
             "action": {
                 "type": "ignore-previous-rules"
```

</details>

The first added test case passes. This shows that `"||allestörungen.at^$third-party"` is properly punycoded to `...xn--allestrungen-9ib\\.at`.

The second added test case fails. The output contains `"*allestörungen.at"` rather than the expected `"*xn--allestrungen-9ib.at"`.

**Comment by antonok-edm** [comment]
837cac43a6f9e218b82dd635e7dfcc18e90a788a should do the trick - thanks so much for the report and the test cases :smile:
