### ISSUE TITLE
Support standard and aggressive filter flags

### ISSUE THREAD

**Issue by ryanbr** [brave/adblock-rust#174]
Support for `$standard`  and/or `$aggressive` adblock filter switches. To allow a Brave-specific AdBlock filter to only apply in certain shield modes.  Avoiding any hardcoded work arounds.

So something like `@@||improving.duckduckgo.com^` would become `@@||improving.duckduckgo.com^$~aggressive`  or `@@||improving.duckduckgo.com^$standard`.

Ref: https://github.com/brave/brave-browser/issues/16133

**Comment by antonok-edm** [comment]
@ryanbr this sounds like a good use-case for the `$tag` option, i.e. `$tag=aggressive` - then no new syntax is needed in `adblock-rust`.
