### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [brave/adblock-rust#180]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by antonok-edm** [comment]
Hey @JamieSlome, thanks for the heads up! I'll check with Brave's security team about what I should use here as a `SECURITY.md`, but in the meantime you should be able to refer to [the one from the `brave-browser` repo](https://github.com/brave/brave-browser/blob/master/SECURITY.md).

**Comment by antonok-edm** [comment]
I've just added [`SECURITY.md`](https://github.com/brave/adblock-rust/blob/master/SECURITY.md) to the repository.

**Comment by antonok-edm** [comment]
@JamieSlome any updates on the security issue?

**Comment by JamieSlome** [comment]
@antonok-edm - you can view the advisory [here](https://huntr.dev/bounties/1625950102554-brave/adblock-rust/).

It was marked as invalid as our program does not accept non-code level vulnerabilities, but feel free to use the page for your reference.
