### ISSUE TITLE
Support parsing multiple aliases from uBO resources

### ISSUE THREAD

**Issue by ryanbr** [brave/adblock-rust#187]
Opening `https://www.uploadbank.com/m38g85tihk7k`  would issue a warning. 
![image (12)](https://user-images.githubusercontent.com/1659004/135378666-0dd5af38-7482-4ffe-9e3e-f9245a4e5545.png)

uBO uses `uploadbank.com##+js(no-setTimeout-if, appendChild)` to get around this. Which doesn't work in Brave

Total active uBO filters: 
`uploadbank.com##+js(no-setTimeout-if, appendChild)`
`uploadbank.com##+js(no-setInterval-if, visibility, 1000)`
`uploadbank.com##+js(window.open-defuser)`

Test case: https://gorhill.github.io/uBlock/tests/scriptlet-injection-filters-1.html   (which fails on the top testcase)

Tested in Version 1.32.31 Chromium: 94.0.4606.61 (Official Build) nightly (64-bit)

**Comment by antonok-edm** [comment]
Looks like `no-setTimeout-if` is the first scriptlet from `scriptlets.js` with multiple aliases. While I don't necessarily agree with the choice to have several different syntaxes for achieving the exact same injection, I did anticipate this happening at some point in the data structure I chose for these resources. I will still need to update the parsing logic to handle it - currently there's just one field in the parser that gets overwritten by the most recently found `/// alias` line.

This should help with the newer `abort-current-script` scriptlet as well, which has 3(!?) aliases in addition to the actual name of the scriptlet.

**Comment by kjozwiak** [comment]
Verified this is working 👍 Visited `https://www.uploadbank.com/m38g85tihk7k` and was able to download/view the file without running into the above modal. Used the following build for the above verification:

```
Brave | 1.32.40 Chromium: 94.0.4606.71 (Official Build) nightly (64-bit)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | Windows 10 Version 20H2 (Build 19042.1266)
```

Used the following `component` for the above verification:

```
Brave Ad Block Updater - Version: 1.0.1084
```
