### ISSUE TITLE
Add yektanet.com to ad blocker

### ISSUE THREAD

**Issue by web-dragon-smsp** [brave/adblock-rust#198]
Hello. I use Brave Browser and I really like it. But there is an issue Brave don't  blocks ads from yektanet.com. Please add support for that

**Comment by antonok-edm** [comment]
@web-dragon-smsp thanks for letting us know. I've reported this internally, but in the future if you have reports for specific sites, please file them under https://github.com/brave/brave-browser or post them to https://community.brave.com/.

**Comment by ryanbr** [comment]
@web-dragon-smsp which platform are you on? If on desktop, brave://adblock enabling `IRN: AdBlock Iran Filter` list should cover this.

**Comment by web-dragon-smsp** [comment]
Hello @ryanbr. **It's work**. Thank you a lot.
I really love brave browser and brave team
