### ISSUE TITLE
How about developing Brave Adblock extension/add-on ?

### ISSUE THREAD

**Issue by Doimatcuabautroi** [brave/adblock-rust#202]
Can you develope a Brave Adblock extension/add-on for all browser ?

**Comment by riil93** [comment]
brave tidak bekerja untuk menghasilkan uang di saya..kenapa ya

Pada Sabtu, 26 Maret 2022, Doimatcuabautroi ***@***.***>
menulis:

**Comment by antonok-edm** [comment]
@Doimatcuabautroi `adblock-rust` has benefits over other adblock engines written in JS, but the Chromium patches in Brave Browser itself provide some additional privacy and blocking benefits that aren't possible using extension APIs. Extensions also will be subject to the removal of Manifest v2 in Chrome and potentially other browsers, which would severely limit adblocker extensions' abilities.

If anyone from the community is interested in building an adblock extension based on `adblock-rust`'s engine we'd be happy to assist with making relevant APIs available and documented, but Brave's primary focus is on providing a best-in-class full-browser solution.
