### ISSUE TITLE
Build badge is broken

### ISSUE THREAD

**Issue by yadunandanbhat** [brave/adblock-rust#209]
See below.
![image](https://user-images.githubusercontent.com/54680617/164038302-2c0b5ad9-66bc-413f-a65c-75601eb4b47d.png)
Can I open a pr for this?

**Comment by antonok-edm** [comment]
@yadunandanbhat good catch, of course you're welcome to open a PR :smile: 

cc @mihaiplesa

**Comment by mihaiplesa** [comment]
Fixed in https://github.com/brave/adblock-rust/commit/d390a3cf85848541de7f7de0e7eb59484f55c234
