### ISSUE TITLE
Support for xml resources

### ISSUE THREAD

**Issue by alkim0** [brave/adblock-rust#223]
In uBlock's redirection-engine.js. There is "noop-vmap1.0.xml". I imagine this gets translated to a mime type of "Unknown", but it really seems like there should be a separate TextXml type for it.

**Comment by antonok-edm** [comment]
Thanks for the report! Somehow I missed it but this should be fixed in the latest release as of https://github.com/brave/adblock-rust/commit/94152423e0d73722391afa3788ce883cbc38fd2b
