### ISSUE TITLE
Support for scriptlet-injection exceptions in Brave's Adblock [Feature Request]

### ISSUE THREAD

**Issue by ghost** [brave/adblock-rust#233]
This is something I hope can be added to Brave's adblocker.

uBlock filter list pushed an update that broke nexusmods.com, they added `nexusmods.com##+js(set, areAdsBlocked, false)` which is breaking both, uBlock and Brave.
The thing is uBlock allows to add `nexusmods.com#@#+js(set, areAdsBlocked, false) ` and the problem would be solved, but brave can't do that, and now we have to wait for uBlock to realize they broke it, to fix it and then Brave get the update to be able to use it.

This has happened sometimes in the past, and it is the same issue since Default lists can't be turned off yet, then, there is no way to really workaround not so great or really bad scriptlet-injection rules. 

uBlock even allows to `nexusmods.com#@#+js()` to whitelist every scriptlet-injection filters in the page, but just use one individually 
would be enough.
But it would still be nice if Brave added `#@#+js()` feature as well if possible, so it would be easier to troubleshoot and see if any scriptlet-injection might be causing issues in general, since Brave doesn't have a logger for scriptlet-injection or cosmetics, it is kind of hard to know what rules are being used Brave adblock, so sometimes whitelist everything, exactly like when $ghide is being used.

Thank you!

**Comment by antonok-edm** [comment]
I will note that in Brave you can visit `brave://components` and trigger a manual update to the `Brave Ad Block Updater` (lists) and/or `Brave Ad Block Resources Library` (scriptlets and `$redirect` resources). Also, there should be a way to disable the default lists at some point.

But, yes, generally it'd be good to support scriptlet injection exceptions.

**Comment by antonok-edm** [comment]
Fixed as of https://github.com/brave/adblock-rust/commit/6408555f0b5f3c03762f5a295d1e629a8413ba7d and released in `v0.8.2`, thanks!
