### ISSUE TITLE
twoway crate is unmaintained

### ISSUE THREAD

**Issue by rillian** [brave/adblock-rust#262]
The `twoway` crate used for fast string matching was recently marked as unmaintained. It would be good to migrate away to avoid triggering audit warnings.

The (former) maintainers recommend using `memchr` but at first glance that supports byte slices but has no equivalent to `twoway::find_str`, so in practice it may need to be some combination of `std::str::find` and `mem(r)chr` with byte string literals and `.as_bytes()` whichever benchmarks better.

**Comment by wknapik** [comment]
When closing this, please also close https://github.com/brave/brave-browser/issues/28228 (but not before the fix is present on all release branches, or the issue will be automatically reopened).

**Comment by antonok-edm** [comment]
Just noting that `memchr` does have [`memmem`](https://docs.rs/memchr/latest/memchr/memmem/index.html) for substring find.

**Comment by rillian** [comment]
:pray:
