### ISSUE TITLE
appnee.com

### ISSUE THREAD

**Issue by u9y8nbwx** [brave/adblock-rust#282]
Even though using the same filters as UbO, I always got redirected to a third party site. Before that, it told me `Please disable your adblock or script blockers to view this page, and wait for a few seconds.` This doesn't happen with UbO.

p/s: even if I disabled Shield, the behavior is still the same.

**Comment by antonok-edm** [comment]
@u9y8nbwx I'm struggling to reproduce any issues on https://appnee.com, can you provide more details about what specific link(s) you're clicking on?

**Comment by u9y8nbwx** [comment]
> @u9y8nbwx I'm struggling to reproduce any issues on https://appnee.com, can you provide more details about what specific link(s) you're clicking on?

appnee.com itself. When I typed appnee.com and press enter, it will first show an empty page with `Please disable your adblock or script blockers to view this page, and wait for a few seconds.` then it redirect me to shopee. appnee.com doesn't even allow me to access it!

**Comment by ryanbr** [comment]
What version of Brave are you using? @u9y8nbwx

**Comment by ryanbr** [comment]
Also try force updating Brave Ad Block Updater - Version: 1.0.236 in brave://components/
