### ISSUE TITLE
Support other procedural filters 

### ISSUE THREAD

**Issue by ryanbr** [brave/adblock-rust#293]
Coming from the post; https://www.reddit.com/r/brave_browser/comments/13lnfky/does_brave_now_fully_support_procedural_filtering/

https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters

Currently supporting [:has ](https://github.com/brave/brave-browser/issues/27874)

As of 19/05/2023, Popularity of filters in uBO:

| Filter  | Number of filters used |
| ------------- | ------------- |
| has-text   | 494  |
| upward  | 352 |
| xpath | 49 |
| matches-css  | 48  |
| matches-path  | 7  |
| matches-media | 3 |
| matches-attr | 2  |
| watch-attr  | 1  |

**Comment by laymonage** [comment]
Just noticed that Brave doesn't support `has-text`. Would be awesome to have that feature!

**Comment by superlex** [comment]
AdGuard lists use :contains() instead of :has-text(), Brave should support both of them.

**Comment by Yuki2718** [comment]
Any news on this? Facebook ads (video pages or on mobile) are unblocked by the lack of `has-text()`.

**Comment by CapSel** [comment]
In the mean time one can use "Stylebot" to match and hide elements using CSS matching.

**Comment by chris-fj** [comment]
Thanks for the suggestion. However, I’m wondering what can StyleBot do that uBlock can’t, because having to install an extension kind of defeats the purpose of having a built-in adblocker. Specially for my use case, where I wanted to do the blocking on an iPhone on which I can’t install any extensions.   
  
  
  
  
  
  
  

  
  
>

**Comment by antonok-edm** [comment]
Added as of https://github.com/brave/adblock-rust/pull/388
