### ISSUE TITLE
Adding swap image support

### ISSUE THREAD

**Issue by ductridev** [brave/adblock-rust#302]
I wonder if you could have an image swap supported instead of hidden ads.
Hopefully, we can have these features.

**Comment by antonok-edm** [comment]
@ductridev can you explain more about what this might look like? You want to replace images on pages with... some other image? What images would you be using as replacements?

FWIW, this technically sorta used to be possible using `background-image: url` CSS style injection filters, but it's a [potential privacy leak](https://github.com/uBlockOrigin/uBlock-issues/issues/668) and so it's definitely not possible in the major adblockers these days.

**Comment by ductridev** [comment]
@antonok-edm by default, the ad block will inject the hidden stylesheet to the ad elements, but I don't want it, I'm building an electron app and it will break some pages when my customers try to access it from my electron apps, so I want to replace the hidden stylesheet with any images which can be configured by my customers.

**Comment by ductridev** [comment]
I hope we can have a function to set the stylesheet injection instead of adding it to filters because I need to keep the filter up to date at EasyList of AdBlockPlus or some EasyList which is hosted on the Internet.

**Comment by antonok-edm** [comment]
@ductridev generally `adblock-rust` doesn't return any stylesheets, just sets of selectors that should be hidden (see https://docs.rs/adblock/latest/adblock/engine/struct.Engine.html#cosmetic-filtering for more details). If you're embedding this into an electron app, you're free to do anything you want with those selectors, including using replacement images.

**Comment by ductridev** [comment]
@antonok-edm thank you, I will try this right away. I will reopen if there is another problem.
