### ISSUE TITLE
Add ublock

### ISSUE THREAD

**Issue by kokofixcomputers** [brave/adblock-rust#308]
Add ublock in here! Because UBlock is more powerfull then this so maybe add ublock! I had no ads after installing ublock but i had ads before when i just installed brave and chosen a lot of filters! Can you make it so that ublock is built in here?

**Comment by antonok-edm** [comment]
@kokofixcomputers using uBlock Origin directly would be problematic for a few reasons, including that we'd be limited to extension APIs. Manifest V2 deprecation is a big problem for uBlock Origin, but not for any of the code used in Brave's adblocker.

That being said...

> I had no ads after installing ublock but i had ads before when i just installed brave and chosen a lot of filters

...if you're encountering ads please tag @ryanbr or myself in a new issue in https://github.com/brave/brave-browser/issues. We'd like to get as many of these cases fixed as possible.
