### ISSUE TITLE
Possible to embed into Firefox ?

### ISSUE THREAD

**Issue by GunGunGun** [brave/adblock-rust#317]
Currently Rust Adblock is only test-able in Brave, but is it possible to embed it into Gecko engine to see how it performs ?

**Comment by antonok-edm** [comment]
@GunGunGun I'm almost certain it's _possible_. But as @MasterKia mentioned, it is also a lot of effort and probably not worth it unless the implementation will be maintained on an ongoing basis.

Brave doesn't have the resources to devote to work on embedding anything in Gecko (personally, I have more than enough to work on in Chromium already :sweat_smile:). That being said, if you or anyone else runs into issues integrating with Gecko, I'm happy to improve the API and/or functionality within `adblock-rust` to better suit the use-case.
