### ISSUE TITLE
Will adblock-rust continue to work after Chrome Manifest V3?

### ISSUE THREAD

**Issue by Marc66** [brave/adblock-rust#325]
A few news releases came out today mentioning that uBlock Origin and the likes will stop working in ~6 months when Manifest V3 is enforced. Will this also affect Brave's native adblocker (which shares similar lists and features as uBlock origin)?

https://www.androidauthority.com/google-chrome-manifest-v3-changes-3386506/

https://www.ghacks.net/2023/11/17/your-chrome-extensions-may-stop-working-in-2024/

**Comment by rmdhnreza** [comment]
MV3 will not affect Brave Ad Blocker because it is not an extension.

**Comment by antonok-edm** [comment]
@rmdhnreza is correct. Brave Shields doesn't use extension APIs, so Brave's native adblocker will continue to work even when Manifest V2 is removed altogether.

In addition, Brave [has committed](https://twitter.com/brave/status/1574822799700541446) to maintaining Manifest V2 beyond Google's deprecation date, so extensions like uBlock Origin will continue to work in Brave, if you still want to use those.

**Comment by Marc66** [comment]
Excellent, thank you
