### ISSUE TITLE
uBlock filter not working on Brave, works on Firefox + uBlock

### ISSUE THREAD

**Issue by chris-fj** [brave/adblock-rust#334]
Hello,

I'm experiencing a weird issue that I asked on the [Brave community](https://community.brave.com/t/ublock-custom-filter-not-working-on-brave-working-on-firefox/532197). Basically, the filters are not being applied even though they work on Firefox + uBlock. Tested on Fedora and Windows. 

The filter is this one

```css
example.org##article:has(span:has-text(/text-i-want-to-match/i))
```
I want to know if there's a way of debugging the filters in Brave or if there's a way of knowing which parts of the syntax are compatible with Brave. I'm opening this issue here (apart from opening on the Brave community) because the help center of Brave (in [How do I manage Ad-Block filters in Brave?](https://support.brave.com/hc/en-us/articles/6449369961741-How-do-I-manage-Ad-Block-filters-in-Brave)) says

> Brave is broadly compatible with uBlock Origin's filter rule syntax. We encourage you to refer to [the uBlock Origin Static filter syntax page](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax).
> 
> Differences in compatibility are treated as bugs and are documented in the [adblock-rust issue tracker](https://github.com/brave/adblock-rust/issues).

Thanks for you help

**Comment by antonok-edm** [comment]
thanks @chris-fj! The filter you mentioned uses `:has-text`, which is a procedural filter operator. I'm currently tracking that in https://github.com/brave/adblock-rust/issues/293.

**Comment by chris-fj** [comment]
Thanks, I’ll track it from there. I tried to search related issues but this didn’t came up because the keywords were not related
