### ISSUE TITLE
Allow specific YouTube channels with the AdBlock

### ISSUE THREAD

**Issue by airton47** [brave/adblock-rust#345]
Basically, create a feature that allows brave's adblock to show ads for specific YouTube Channels even if the protections are globally activated for YouTube the adblock will allow ads only when watching a certain channels's video.

**Comment by spacey-sooty** [comment]
This seems a bit specific for a generalised adblock engine

**Comment by antonok-edm** [comment]
Indeed - this can be done using custom filters in Brave Browser; it's not really applicable to `adblock-rust`. If you're interested in this as a first-class feature of Brave Browser then please file an issue in https://github.com/brave/brave-browser instead.
