### ISSUE TITLE
Add in preexisting filters and keep them updated

### ISSUE THREAD

**Issue by fyreswan** [brave/adblock-rust#37]
I would love the ability to add in a pre-existing filter which will add pages and keep itself updated, just like I can in ublock. So far there is no mechanism to do this under the current Brave Adblock page, unless we individually copy and paste the sites into the free text box.

**Comment by antonok-edm** [comment]
This should be technically supported by `adblock-rust`, it's just not supported by the way it's currently used in Brave. We do have an open issue for this, I recommend adding a +1 over at https://github.com/brave/brave-browser/issues/4891.
