### ISSUE TITLE
Implement cosmetic blocking [tracking]

### ISSUE THREAD

**Issue by antonok-edm** [brave/adblock-rust#38]
Currently, `adblock-rust` only deals with network filtering. There is no mechanism for parsing cosmetic rules and applying them in an efficient manner to pages as they load.

**Comment by antonok-edm** [comment]
Current implementation work is ongoing in the [cosmetic-filters](https://github.com/brave/adblock-rust/tree/cosmetic-filters) branch.

**Comment by szaimen** [comment]
Any update here?

**Comment by antonok-edm** [comment]
@szaimen the current implementation for redirectable resources is being reworked to support uBlock Origin's new `web_accessible_resources` directory (see https://github.com/brave/adblock-rust/pull/50). That directly impacts cosmetic filtering, because some of those resources are scriptlets that can be injected with cosmetic filter rules. This PR should be next in line.
