### ISSUE TITLE
Is brave adblock can read Adguard syntax

### ISSUE THREAD

**Issue by arfshl** [brave/adblock-rust#406]
I want to use this filter:https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt

As they can read by uBO and Adguard, can brave adblock read it too?

**Comment by antonok-edm** [comment]
@arshl Some AdGuard syntax is supported but generally @ChowMein47 is correct, it's primarily designed to work with uBO syntax at the moment.
