### ISSUE TITLE
Don't print errors to STDOUT or STDERR

### ISSUE THREAD

**Issue by snyderp** [brave/adblock-rust#52]
Right now the lib prints errors out (e.g. `Error parsing request, returning no match`) but doesn't show the error to the calling code.  This seems like kinda a worst of all words situation.

It would be better to change the api to allow the caller to (optionally) receive feedback if an error occurred, and print nothing (since my code has no way of replying to the error anyway).  Possibly an optional `throw exception on error` parameter for any option that might have such an error?

**Comment by AndriusA** [comment]
For the request matching calls fixed by #53 

Keeping for now for other execution paths (e.g. serialization/deserialization)
