### ISSUE TITLE
Replace regional (Japanese) ad filters

### ISSUE THREAD

**Issue by rsuwa** [brave/adblock-rust#66]
ABP Japanese filters has a lot of bugs and Japanese ad-blocking users often use 280blocker (<https://280blocker.net/files/280blocker_adblock.txt>) or mochi filter (<https://pokapoka.shoooter.net/>) instead.
They are also updated frequently, so consider changing it.

Or add a feature like ublock origin that lets users subscribe to and sync their favorite ad filters. (Related Issue: <https://github.com/brave/browser-laptop/issues/9711>)

**Comment by ryanbr** [comment]
Closing, We've replaced the previous japanese list with Adguard Japanese. Which is well supported List and easier to submit patches too.
