### ISSUE TITLE
Domain is blocked while it doesn't contain ads

### ISSUE THREAD

**Issue by amr-essam1** [brave/adblock-rust#77]
Hi,  our website speakol.com is listed in the blocked domains as "||speakol.com^$third-party".
While we are serving ads through the platform, the website itself doesn't contain ads. This is badly impacting the user experience as our users can't access their dashboards (advertisers.speakol.com) when using brave browser. Could you please help out with explaining the reason and how to overcome this?

**Comment by pes10k** [comment]
Hi @amr-essam1 .  We pull that rule from EasyList.  You might direct your question to that project, as they'd have more information about the history of the rule.
